name: pkl-release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write
  contents: read
  packages: write
  attestations: write

env:
  OPS_PKG_CRT: ${{ secrets.OPS_PKG_CRT }}
  OPS_PKG_KEY: ${{ secrets.OPS_PKG_KEY }}
  OPS_TREE_CONF: ${{ secrets.OPS_TREE_CONF }}

jobs:
  pkg:
    runs-on: ubuntu-24.04-arm

    if: ${{ github.actor != 'peldroid[bot]' }}

    concurrency:
      group: pkg
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Install just
        uses: extractions/setup-just@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::897722706215:role/github-pel
          role-session-name: PublishSession

      - name: Install Orbital
        run: |
          bash -c "$(curl -fsSL https://hub.platform.engineering/get/setup.sh)" -- install --yes orbital

      - name: Add PEL to PATH
        run: echo "/opt/pel/bin" >> $GITHUB_PATH

      - name: Build
        run: just

      - name: Publish
        run: just publish